spring.application.name=user-service
server.port=7086
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
spring.datasource.url=jdbc:mysql://localhost:3306/smarttms
spring.datasource.username=root
spring.datasource.password=mysqlpass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:smarttms@123}
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

# Logging
logging.level.com.smartlogistics.userservice=DEBUG
logging.level.org.springframework.cache=DEBUG


# Observability / Tracing / Metrics
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.metrics.tags.application=${spring.application.name}

# Config Server Client
spring.config.import=optional:configserver:http://localhost:8888
