spring.application.name=auth-service
server.port=7083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
jwt.secret=c21hcnRsb2dpc3RpY3Nqd3RzZWNyZXRrZXlzbWFydGxvZ2lzdGljc2p3dHNlY3JldGtleQ==
spring.datasource.url=jdbc:mysql://localhost:3306/smarttms
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
