spring.application.name=eureka-server
server.port=8761
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Observability / Tracing / Metrics
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.metrics.tags.application=${spring.application.name}

# Config Server Client
spring.config.import=optional:configserver:http://localhost:8888
