spring.application.name=order-service
server.port=7084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
spring.datasource.url=jdbc:mysql://localhost:3306/smarttms
spring.datasource.username=root
spring.datasource.password=mysqlpass
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.acks=all
spring.kafka.producer.retries=2
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

app.kafka.topics.order-events=${ORDER_EVENTS_TOPIC:order-events}
app.kafka.publish.max-attempts=${KAFKA_PUBLISH_MAX_ATTEMPTS:3}
app.kafka.publish.backoff-ms=${KAFKA_PUBLISH_BACKOFF_MS:500}


# Observability / Tracing / Metrics
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.metrics.tags.application=${spring.application.name}

# Config Server Client
spring.config.import=optional:configserver:http://localhost:8888

# Resilience4j Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.failureRateThreshold=50
resilience4j.circuitbreaker.instances.default.waitDurationInOpenState=10000ms
resilience4j.circuitbreaker.instances.default.permittedNumberOfCallsInHalfOpenState=3
